// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djqkwgivgfudjcqhpxap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqcWt3Z2l2Z2Z1ZGpjcWhweGFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODMzODksImV4cCI6MjA2Mzg1OTM4OX0.2UeQQ0m-_uyjih4TTIg2UeonlwnvtinPxmA3IVNEQk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);